#!/usr/bin/env bash
# Подставной getent: домен резолвится в $MOCK_PUBLIC_IP, если нет $MOCK_STATE/dns_fail
echo "getent $*" >> "$MOCK_LOG"
[[ -f $MOCK_STATE/dns_fail ]] && exit 2
echo "${MOCK_PUBLIC_IP:-203.0.113.50} STREAM ${2:-}"
